name: CI Build

on:
  push:
    branches: [ master ]
    tags:
    - '*'
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/muhkuh-sys/mbs_ubuntu_2004_x86_64:latest
    steps:
    - name: Checkout repository
      # Use the old checkout v1 here. The newer v2 requires git 2.28 which is not available in the standard distribution.
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install build requirements
      run: ./.install_build_requirements
    - name: Install NPM modules
      run: npm install
    - name: Build web frontend
      run: npm run release
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: targets/www
